### ISSUE TITLE
Stepmania will not startup when using Transcendence

### ISSUE THREAD

**Issue by jamuwu** [MinaciousGrace/Transcendence#1] opened 2016-02-12 23:30 UTC
```
jamesguessis@senpai-chan /home/jamesguessis/Games/Stepmania $ ./stepmania 
StepMania5.1-git-e7539c8
Compiled 20151030 @ 22:48:39 (build e7539c8)
Log starting 2016-02-12 18:27:11
Loading window: gtk
OS: Linux ver 031900
Crash backtrace component: x86 custom backtrace
Crash lookup component: backtrace_symbols
Runtime library: glibc 2.19
Threads library: NPTL 2.19
libavcodec: 0x372765 (3614565)
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:237: table index is nil
WARNING: /Scripts/00 settings_system.lua:237: main(settings_prefix = /_fallback_settings/,slot_to_prof_dir = (null),load_conf_file = (null),setting_mt = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = table index is nil)
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
WARNING: /Scripts/00 settings_system.lua:71: load(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/_fallback_settings/avatarConfig.lua,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'DeepCopy' (a nil value))
WARNING: /Scripts/01 avatar_config.lua:8: main(defaultConfig = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
WARNING: /Scripts/00 settings_system.lua:71: load(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/_fallback_settings/colorConfig.lua,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'DeepCopy' (a nil value))
WARNING: /Scripts/01 color_config.lua:116: main(defaultConfig = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
WARNING: /Scripts/00 settings_system.lua:71: load(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/_fallback_settings/themeConfig.lua,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'DeepCopy' (a nil value))
WARNING: /Scripts/01 theme_config.lua:37: main(defaultConfig = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/02 Branches.lua:11: attempt to call global 'ivalues' (a nil value)
WARNING: /Scripts/02 Branches.lua:11: SMOnlineScreen((*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'ivalues' (a nil value))
WARNING: /Scripts/02 Branches.lua:147: main((*temporary) = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/03 CustomSpeedMods.lua:97: attempt to call global 'split' (a nil value)
WARNING: /Scripts/03 CustomSpeedMods.lua:97: StringToModTable(str = 0.5x,1x,1.5x,2x,3x,4x,5x,6x,7x,8x,C250,C450,m550,mods = (null),valid = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = ,,(*temporary) = 0.5x,1x,1.5x,2x,3x,4x,5x,6x,7x,8x,C250,C450,m550,(*temporary) = attempt to call global 'split' (a nil value))
WARNING: /Scripts/03 CustomSpeedMods.lua:137: main(ProfileSpeedMods = (null),EmptyModTable = (null),MergeInModTable = (null),CanonicalizeMod = (null),StringToModTable = (null),ModTableToList = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
WARNING: /Scripts/00 settings_system.lua:71: load(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/_fallback_settings/ghostData.lua,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'DeepCopy' (a nil value))
WARNING: /Scripts/GhostData.lua:8: main(ghostData = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:160: bad argument #1 to 'pairs' (table expected, got nil)
WARNING: [C]: pairs( = (null))
WARNING: /Scripts/00 settings_system.lua:160: lua_table_to_string(t = (null),indent = ,line_pos = 1,internal_indent =   ,ret = {,has_table = (null))
WARNING: /Scripts/00 settings_system.lua:118: save(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/_fallback_settings/themeConfig.lua,file_handle = (null),(*temporary) = return )
WARNING: /Scripts/PrefsOverride.lua:27: main()
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:237: table index is nil
WARNING: /Scripts/00 settings_system.lua:237: main(settings_prefix = /Default_settings/,slot_to_prof_dir = (null),load_conf_file = (null),setting_mt = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = table index is nil)
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
WARNING: /Scripts/00 settings_system.lua:71: load(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/Default_settings/avatarConfig.lua,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'DeepCopy' (a nil value))
WARNING: /Scripts/01 avatar_config.lua:8: main(defaultConfig = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
WARNING: /Scripts/00 settings_system.lua:71: load(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/Default_settings/colorConfig.lua,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'DeepCopy' (a nil value))
WARNING: /Scripts/01 color_config.lua:116: main(defaultConfig = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
WARNING: /Scripts/00 settings_system.lua:71: load(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/Default_settings/themeConfig.lua,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'DeepCopy' (a nil value))
WARNING: /Scripts/01 theme_config.lua:37: main(defaultConfig = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/02 Branches.lua:11: attempt to call global 'ivalues' (a nil value)
WARNING: /Scripts/02 Branches.lua:11: SMOnlineScreen((*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'ivalues' (a nil value))
WARNING: /Scripts/02 Branches.lua:147: main((*temporary) = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/03 CustomSpeedMods.lua:97: attempt to call global 'split' (a nil value)
WARNING: /Scripts/03 CustomSpeedMods.lua:97: StringToModTable(str = 0.5x,1x,1.5x,2x,3x,4x,5x,6x,7x,8x,C250,C450,m550,mods = (null),valid = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = ,,(*temporary) = 0.5x,1x,1.5x,2x,3x,4x,5x,6x,7x,8x,C250,C450,m550,(*temporary) = attempt to call global 'split' (a nil value))
WARNING: /Scripts/03 CustomSpeedMods.lua:137: main(ProfileSpeedMods = (null),EmptyModTable = (null),MergeInModTable = (null),CanonicalizeMod = (null),StringToModTable = (null),ModTableToList = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
WARNING: /Scripts/00 settings_system.lua:71: load(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/Default_settings/ghostData.lua,(*temporary) = (null),(*temporary) = (null),(*temporary) = (null),(*temporary) = attempt to call global 'DeepCopy' (a nil value))
WARNING: /Scripts/GhostData.lua:8: main(ghostData = (null))
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:160: bad argument #1 to 'pairs' (table expected, got nil)
WARNING: [C]: pairs( = (null))
WARNING: /Scripts/00 settings_system.lua:160: lua_table_to_string(t = (null),indent = ,line_pos = 1,internal_indent =   ,ret = {,has_table = (null))
WARNING: /Scripts/00 settings_system.lua:118: save(self = (null),slot = ProfileSlot_Invalid,prof_dir = Save,fname = Save/Default_settings/themeConfig.lua,file_handle = (null),(*temporary) = return )
WARNING: /Scripts/PrefsOverride.lua:27: main()
/////////////////////////////////////////
/////////////////////////////////////////
WARNING: ReadFile(Save/ThemePrefs.ini): No such file or directory
/////////////////////////////////////////
Sound writeahead has been overridden to 1
Language: en
Theme: default
Error: Couldn't find a sound driver that works
```

This is the output when I try to open stepmania now

**Comment by MinaciousGrace** [comment] 2016-02-14 17:04
I'm not exactly sure what's happening but this is most likely a symptom of a broader issue involving the game panicking and setting everything to fallback settings if it can't start the renderer. In most people's cases this results in all settings being reverted to default for seemingly no reason.

It appears in your case that its trying to use defaults that aren't supported for whatever reason, resulting in the game being unable to start (looks like the sound driver?). Hopefully this issue is fixed with the most recent update but I haven't been able to reproduce the problem on my end so I don't know for sure. 

in any case the other solution is to remove prefsoverride.lua from the theme before using it for the first time

**Comment by kyzentun** [comment] 2016-02-28 03:21
```
WARNING: Lua runtime error: /Scripts/00 settings_system.lua:71: attempt to call global 'DeepCopy' (a nil value)
```

If DeepCopy is nil, then something went wrong loading the _fallback theme, which provides DeepCopy.

Forcing the sound driver to WaveOut will prevent starting up on any platform other than Windows, because stepmania gives up if the sound driver chosen by the preference can't be loaded.

**Closed as completed** 2022-04-20 16:01 UTC
